name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행
  pull_request:
    branches:
      - main  # main 브랜치에 대한 PR이 생길 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 레포지토리의 코드를 체크아웃

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies for Next.js
      run: |
        cd next-app
        npm install

    - name: Build Next.js
      run: |
        cd next-app
        npm run build

    - name: Deploy Next.js to S3
      run: |
        aws s3 sync next-app/out/ s3://my-next-app-bucket-e57x1l --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION_FRONT }}

    - name: Build and deploy Nest.js to App Runner
      run: |
        cd nest-api
        docker build -t nest-api . 
        docker tag nest-api:latest 743316907132.dkr.ecr.us-east-1.amazonaws.com/nest-api:latest
        
        # Login to AWS ECR
        aws ecr get-login-password --region ${{ secrets.AWS_REGION_BACK }} | docker login --username AWS --password-stdin 743316907132.dkr.ecr.us-east-1.amazonaws.com
        
        # Push the image to ECR
        docker push 743316907132.dkr.ecr.us-east-1.amazonaws.com/nest-api:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION_BACK }}

    - name: Get CloudFront URL
      run: |
        # Use AWS CLI to get the CloudFront distribution domain name
        export CLOUDFRONT_URL=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[0]=='my-next-app-bucket-${{ secrets.AWS_REGION_FRONT }}'].DomainName" --output text)
        echo "CloudFront URL is: $CLOUDFRONT_URL"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION_FRONT }}
